name: clay
author: Emil Persson <emil.n.persson@gmail.com>
homepage: http://github.com/emilniklas/dart-clay
version: 0.1.0
environment:
  sdk: '>=1.0.0 <2.0.0'
description: A code generator API
dependencies:
  console: '>=2.2.3 <3.0.0'
  path: '>=1.3.5 <2.0.0'
